TUNE-6176: Fix some compiler warnings
Host compilation failed due to the following warnings:

,----
| N      src/builtin.h
| make --no-print-directory all-recursive
| Making all in doc
| make[2]: Nothing to be done for 'all'.
|   CC       profiles/aui/bluetoothd-aui.o
| profiles/aui/aui.c: In function ‘on_aui_ble_get_abs_volume’:
| profiles/aui/aui.c:111:10: error: pointer targets in passing argument 1 of ‘strcpy’ differ in signedness [-Werror=pointer-sign]
|    strcpy(btd_volume, "0.0");
|           ^
| In file included from profiles/aui/aui.c:25:0:
| /usr/include/string.h:129:14: note: expected ‘char * __restrict__’ but argument is of type ‘uint8_t *’
|  extern char *strcpy (char *__restrict __dest, const char *__restrict __src)
|               ^
| profiles/aui/aui.c:115:11: error: pointer targets in passing argument 1 of ‘sprintf’ differ in signedness [-Werror=pointer-sign]
|    sprintf(btd_volume, "%f", dbus_volume);
|            ^
| In file included from ./lib/bluetooth/bluetooth.h:33:0,
|                  from ./src/adapter.h:25,
|                  from profiles/aui/aui.c:27:
| /usr/include/stdio.h:364:12: note: expected ‘char * __restrict__’ but argument is of type ‘uint8_t *’
|  extern int sprintf (char *__restrict __s,
|             ^
| profiles/aui/aui.c: In function ‘volumed_proxy_init’:
| profiles/aui/aui.c:185:15: error: unused variable ‘proxy’ [-Werror=unused-variable]
|   GDBusProxy  *proxy;
|                ^
`----

Fix these, and replace strcpy, sprintf with their size-checking versions.